# Generated by Django 4.1.7 on 2023-02-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
